var axel=Math.random()+"";var ord=axel*1000000000000000000;var movedAds=new Array();function urlPath(urlstr){if(urlstr.indexOf("://")>=0){urlstr=urlstr.substring(urlstr.indexOf("://")+3);urlstr=urlstr.indexOf("/")?urlstr.substring(urlstr.indexOf("/")):"/";}
return urlstr;}
function moveAd(ad){try{movedAds[ad]="#ad"+ad;banner_system=document.getElementById(ad);banner_data=document.getElementById("ad"+ad);banner_system.appendChild(banner_data);banner_data.style.display='block';banner_system.style.display='block';}catch(e){}};function toggleTheme(theme){var pos=$("#theme").attr("href").lastIndexOf("/");$("#theme").attr("href",$("#theme").attr("href").substr(0,pos)+"/screen_"+theme+".css");$.cookie("fantasy",theme,{expires:31,path:"/"});};$(document).ready(function(){for(ad in movedAds){if($(movedAds[ad]+" img[src$='/misc/trans.png']").length>=1){$(movedAds[ad]).parents(".media").parent().remove();}}
if($.cookie("sonic")){$(".tablesummarysupport").addClass("tablesummary");$(".detailicon").html("Detailed List").addClass("summaryicon");}
$(".toggletabledetail").click(function(){if($.cookie("sonic")){$(".tablesummarysupport").removeClass("tablesummary");$(this).html("Summary List").removeClass("summaryicon");$.cookie("sonic",null,{path:"/"});}else{$(".tablesummarysupport").addClass("tablesummary");$(this).html("Detailed List").addClass("summaryicon");$.cookie("sonic",true,{path:"/"});}
return false;});$.fn.showHtml=function(html,speed){this.each(function(){var el=$(this);var finish={width:this.style.width,height:this.style.height};var cur={width:el.width()+"px",height:el.height()+"px"};el.html(html);var next={width:el.width()+"px",height:el.height()+"px"};el.css(cur).animate(next,speed,function(){el.css(finish);});});};$.fn.toggleDescription=function(field){$("#"+field+"description").hide();$(this).append(' <a href="#" id="toggle'+field+'description">read more +</a>');$("#toggle"+field+"description").toggle(function(){$(this).html("hide detail -");$("#"+field+"description").slideDown();return false;},function(){$(this).html("read more +");$("#"+field+"description").slideUp();return false;});};$.fn.saveUpdate=function(action,callback,confirmtxt,microtimeout){$(this).click(function(){if(!confirmtxt||(confirmtxt&&confirm(confirmtxt))){if($(this).hasClass('ajaxicon')){$(this).html('Please Wait...');}else{text=$(this).html();currentoption=$(this);if($(this).addClass('ajaxicon').attr('href').indexOf('?')>0){var arguments=$(this).attr('href').split('?');var urlstr=arguments[0];var datastr="&"+arguments[1];}else{var urlstr=$(this).attr('href');var datastr="";}
$.ajax({type:'POST',url:urlPath(urlstr),timeout:(microtimeout?microtimeout:60000),dataType:'json',data:"ajax=t"+datastr,error:function(response,error,exception){currentoption.removeClass('ajaxicon').html(text);$.achtung({message:'An error has occured updating the item requested. Please try again shortly.',className:'achtungFail',timeout:5});},success:function(response){currentoption.removeClass('ajaxicon').html(text);if(response['error']){$.achtung({message:response['text'],className:'achtungFail',timeout:typeof response["timeout"]=="number"&&response["timeout"]>0?response["timeout"]:10});}else if(response['text']){$.achtung({message:response['text'],className:'achtungSuccess',timeout:typeof response["timeout"]=="number"&&response["timeout"]>0?response["timeout"]:10});}
if(response['labels']){for(i in response['labels']){currentoption.parent().find("."+i+"icon").attr("title",response['labels'][i]).html(response['labels'][i]).change();}}
if(response['hidetooltip']){if(currentoption.parents('.sidecolumn').length>0){$('.headernormalbox .errortooltip').removeClass('errortooltip').text('');}else{currentoption.parents('.normalbox').find('.errortooltip').removeClass('errortooltip').text('');}}
if(callback){callback(currentoption,response);}
if(response['alert']){$.achtung({message:response['alert']});}}});}}
return false;});};$(".swapvalue").each(function(i){$(this).focus(function(){if($(this).hasClass("swapvaluesmart")){$(this).val($(this).val().replace($(this).attr("alt"),""));}else if($(this).val()==$(this).attr("alt")){$(this).val("");}}).blur(function(){if($.trim($(this).val())==""){$(this).val($(this).attr("alt"));}}).blur();});savedStats=[];saveStat=function(url,area,id,type){if(savedStats[id]){return true;}else{$.post(urlPath(url),{sitearea:area,siteareaid:id,type:type});}
savedStats[id]=true;};});jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options.expires=-1;}
var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toUTCString();}
var path=options.path?'; path='+options.path:'';var domain=options.domain?'; domain='+options.domain:'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break;}}}
return cookieValue;}};;(function($){var colorbox='colorbox',hover='hover',TRUE=true,FALSE=false,cboxPublic,isIE=$.browser.msie&&!$.support.opacity,isIE6=isIE&&$.browser.version<7,cbox_open='cbox_open',cbox_load='cbox_load',cbox_complete='cbox_complete',cbox_cleanup='cbox_cleanup',cbox_closed='cbox_closed',cbox_resize='resize.cbox_resize',$overlay,$cbox,$wrap,$content,$topBorder,$leftBorder,$rightBorder,$bottomBorder,$related,$window,$loaded,$loadingBay,$loadingOverlay,$loadingGraphic,$title,$current,$slideshow,$next,$prev,$close,interfaceHeight,interfaceWidth,loadedHeight,loadedWidth,element,bookmark,index,settings,open,active,defaults={transition:"elastic",speed:350,width:FALSE,height:FALSE,innerWidth:FALSE,innerHeight:FALSE,initialWidth:"400",initialHeight:"400",maxWidth:FALSE,maxHeight:FALSE,scalePhotos:TRUE,scrolling:TRUE,inline:FALSE,html:FALSE,iframe:FALSE,photo:FALSE,href:FALSE,title:FALSE,rel:FALSE,opacity:0.9,preloading:TRUE,current:"image {current} of {total}",previous:"previous",next:"next",close:"close",open:FALSE,overlayClose:TRUE,slideshow:FALSE,slideshowAuto:TRUE,slideshowSpeed:2500,slideshowStart:"start slideshow",slideshowStop:"stop slideshow",onOpen:FALSE,onLoad:FALSE,onComplete:FALSE,onCleanup:FALSE,onClosed:FALSE};function setSize(size,dimension){dimension=dimension==='x'?$window.width():$window.height();return(typeof size==='string')?Math.round((size.match(/%/)?(dimension/100)*parseInt(size,10):parseInt(size,10))):size;}
function isImage(url){url=$.isFunction(url)?url.call(element):url;return settings.photo||url.match(/\.(gif|png|jpg|jpeg|bmp)(?:\?([^#]*))?(?:#(\.*))?$/i);}
function process(){for(var i in settings){if($.isFunction(settings[i])&&i.substring(0,2)!=='on'){settings[i]=settings[i].call(element);}}
settings.rel=settings.rel||element.rel;settings.href=settings.href||element.href;settings.title=settings.title||element.title;}
function launch(elem){element=elem;settings=$(element).data(colorbox);process();if(settings.rel&&settings.rel!=='nofollow'){if(settings.rel.indexOf('=')!=-1){$related=$(element);index=0;settingsarray=settings.rel.split(';');for(settingarray in settingsarray){settingtemp=settingsarray[settingarray].split('=');settings[settingtemp[0]]=settingtemp[1];}}else{$related=$('.cboxElement').filter(function(){var relRelated=$(this).data(colorbox).rel||this.rel;return(relRelated===settings.rel);});index=$related.index(element);if(index<0){$related=$related.add(element);index=$related.length-1;}}}else{$related=$(element);index=0;}
if(!open){open=TRUE;active=TRUE;bookmark=element;bookmark.blur();$(document).bind("keydown.cbox_close",function(e){if(e.keyCode===27){e.preventDefault();cboxPublic.close();}}).bind("keydown.cbox_arrows",function(e){if($related.length>1){if(e.keyCode===37){e.preventDefault();$prev.click();}else if(e.keyCode===39){e.preventDefault();$next.click();}}});if(settings.overlayClose){$overlay.css({"cursor":"pointer"}).one('click',cboxPublic.close);}
$.event.trigger(cbox_open);if(settings.onOpen){settings.onOpen.call(element);}
$overlay.css({"opacity":settings.opacity}).show();settings.w=setSize(settings.initialWidth,'x');settings.h=setSize(settings.initialHeight,'y');cboxPublic.position(0);if(isIE6){$window.bind('resize.cboxie6 scroll.cboxie6',function(){$overlay.css({width:$window.width(),height:$window.height(),top:$window.scrollTop(),left:$window.scrollLeft()});}).trigger("scroll.cboxie6");}}
$current.add($prev).add($next).add($slideshow).add($title).hide();$close.html(settings.close).show();cboxPublic.slideshow();cboxPublic.load();}
cboxPublic=$.fn.colorbox=function(options,callback){var $this=this;if(!$this.length){if($this.selector===''){$this=$('<a/>');options.open=TRUE;}else{return this;}}
$this.each(function(){var data=$.extend({},$(this).data(colorbox)?$(this).data(colorbox):defaults,options);$(this).data(colorbox,data).addClass("cboxElement");if(callback){$(this).data(colorbox).onComplete=callback;}});if(options&&options.open){launch($this);}
return this;};cboxPublic.showOverlay=function(){$overlay.css({"opacity":cboxPublic.settings.opacity}).show();};cboxPublic.hideOverlay=function(){$overlay.css({cursor:'auto'}).fadeOut('fast');};cboxPublic.setHeight=function(newheight){if(!open){return;}
var speed=settings.transition==="none"?0:settings.speed;$window.unbind(cbox_resize);settings.h=newheight;$loaded.css({width:settings.w,height:settings.h});cboxPublic.position(speed);};cboxPublic.init=function(){function $div(id){return $('<div id="cbox'+id+'"/>');}
$window=$(window);$cbox=$('<div id="colorbox"/>');$overlay=$div("Overlay").hide();$wrap=$div("Wrapper");$content=$div("Content").append($loaded=$div("LoadedContent").css({width:0,height:0}),$loadingOverlay=$div("LoadingOverlay"),$loadingGraphic=$div("LoadingGraphic"),$title=$div("Title"),$current=$div("Current"),$slideshow=$div("Slideshow"),$next=$div("Next"),$prev=$div("Previous"),$close=$div("Close"));$wrap.append($('<div/>').append($div("TopLeft"),$topBorder=$div("TopCenter"),$div("TopRight")),$('<div/>').append($leftBorder=$div("MiddleLeft"),$content,$rightBorder=$div("MiddleRight")),$('<div/>').append($div("BottomLeft"),$bottomBorder=$div("BottomCenter"),$div("BottomRight"))).children().children().css({'float':'left'});$loadingBay=$("<div style='position:absolute; top:0; left:0; width:9999px; height:0;'/>");$('body').prepend($overlay,$cbox.append($wrap,$loadingBay));if(isIE){$cbox.addClass('cboxIE');if(isIE6){$overlay.css('position','absolute');}}
$content.children().bind('mouseover mouseout',function(){$(this).toggleClass(hover);}).addClass(hover);interfaceHeight=$topBorder.height()+$bottomBorder.height()+$content.outerHeight(TRUE)-$content.height();interfaceWidth=$leftBorder.width()+$rightBorder.width()+$content.outerWidth(TRUE)-$content.width();loadedHeight=$loaded.outerHeight(TRUE);loadedWidth=$loaded.outerWidth(TRUE);$cbox.css({"padding-bottom":interfaceHeight,"padding-right":interfaceWidth}).hide();$next.click(cboxPublic.next);$prev.click(cboxPublic.prev);$close.click(cboxPublic.close);$content.children().removeClass(hover);$('.cboxElement').live('click',function(e){if(e.button!==0&&typeof e.button!=='undefined'){return TRUE;}else{launch(this);return FALSE;}});};cboxPublic.position=function(speed,loadedCallback){var
animate_speed,winHeight=$window.height(),posTop=Math.max(winHeight-settings.h-loadedHeight-interfaceHeight,0)/2+$window.scrollTop(),posLeft=Math.max(document.documentElement.clientWidth-settings.w-loadedWidth-interfaceWidth,0)/2+$window.scrollLeft();animate_speed=($cbox.width()===settings.w+loadedWidth&&$cbox.height()===settings.h+loadedHeight)?0:speed;$wrap[0].style.width=$wrap[0].style.height="9999px";function modalDimensions(that){$topBorder[0].style.width=$bottomBorder[0].style.width=$content[0].style.width=that.style.width;$loadingGraphic[0].style.height=$loadingOverlay[0].style.height=$content[0].style.height=$leftBorder[0].style.height=$rightBorder[0].style.height=that.style.height;}
$cbox.dequeue().animate({width:settings.w+loadedWidth,height:settings.h+loadedHeight,top:posTop,left:posLeft},{duration:animate_speed,complete:function(){modalDimensions(this);active=FALSE;$wrap[0].style.width=(settings.w+loadedWidth+interfaceWidth)+"px";$wrap[0].style.height=(settings.h+loadedHeight+interfaceHeight)+"px";if(loadedCallback){loadedCallback();}},step:function(){modalDimensions(this);}});};cboxPublic.resize=function(object){if(!open){return;}
var topMargin,prev,prevSrc,next,nextSrc,photo,timeout,speed=settings.transition==="none"?0:settings.speed;$window.unbind(cbox_resize);if(!object){timeout=setTimeout(function(){var $child=$loaded.wrapInner("<div style='overflow:auto'></div>").children();settings.h=$child.height();$loaded.css({height:settings.h});$child.replaceWith($child.children());cboxPublic.position(speed);},1);return;}
$loaded.remove();$loaded=$('<div id="cboxLoadedContent"/>').html(object);function getWidth(){settings.w=settings.w||$loaded.width();settings.w=settings.mw&&settings.mw<settings.w?settings.mw:settings.w;return settings.w;}
function getHeight(){settings.h=settings.h||$loaded.height();settings.h=settings.mh&&settings.mh<settings.h?settings.mh:settings.h;return settings.h;}
$loaded.hide().appendTo($loadingBay).css({width:getWidth(),overflow:settings.scrolling?'auto':'hidden'}).css({height:getHeight()}).prependTo($content);$('#cboxPhoto').css({cssFloat:'none'});if(isIE6){$('select:not(#colorbox select)').filter(function(){return this.style.visibility!=='hidden';}).css({'visibility':'hidden'}).one(cbox_cleanup,function(){this.style.visibility='inherit';});}
function setPosition(s){cboxPublic.position(s,function(){if(!open){return;}
if(isIE){if(photo){$loaded.fadeIn(100);}
$cbox[0].style.removeAttribute("filter");}
if(settings.iframe){$loaded.append("<iframe id='cboxIframe'"+(settings.scrolling?" ":"scrolling='no'")+" name='iframe_"+new Date().getTime()+"' frameborder=0 src='"+settings.href+"' "+(isIE?"allowtransparency='true'":'')+" />");}
$loaded.show();$title.show().html(settings.title);if($related.length>1){$current.html(settings.current.replace(/\{current\}/,index+1).replace(/\{total\}/,$related.length)).show();$next.html(settings.next).show();$prev.html(settings.previous).show();if(settings.slideshow){$slideshow.show();}}
$loadingOverlay.hide();$loadingGraphic.hide();$.event.trigger(cbox_complete);if(settings.onComplete){settings.onComplete.call(element);}
if(settings.transition==='fade'){$cbox.fadeTo(speed,1,function(){if(isIE){$cbox[0].style.removeAttribute("filter");}});}
$window.bind(cbox_resize,function(){cboxPublic.position(0);});});}
if((settings.transition==='fade'&&$cbox.fadeTo(speed,0,function(){setPosition(0);}))||setPosition(speed)){}
if(settings.preloading&&$related.length>1){prev=index>0?$related[index-1]:$related[$related.length-1];next=index<$related.length-1?$related[index+1]:$related[0];nextSrc=$(next).data(colorbox).href||next.href;prevSrc=$(prev).data(colorbox).href||prev.href;if(isImage(nextSrc)){$('<img />').attr('src',nextSrc);}
if(isImage(prevSrc)){$('<img />').attr('src',prevSrc);}}};cboxPublic.load=function(){var href,img,setResize,resize=cboxPublic.resize;active=TRUE;element=$related[index];settings=$(element).data(colorbox);process();$.event.trigger(cbox_load);if(settings.onLoad){settings.onLoad.call(element);}
settings.h=settings.height?setSize(settings.height,'y')-loadedHeight-interfaceHeight:settings.innerHeight?setSize(settings.innerHeight,'y'):FALSE;settings.w=settings.width?setSize(settings.width,'x')-loadedWidth-interfaceWidth:settings.innerWidth?setSize(settings.innerWidth,'x'):FALSE;settings.mw=settings.w;settings.mh=settings.h;if(settings.maxWidth){settings.mw=setSize(settings.maxWidth,'x')-loadedWidth-interfaceWidth;settings.mw=settings.w&&settings.w<settings.mw?settings.w:settings.mw;}
if(settings.maxHeight){settings.mh=setSize(settings.maxHeight,'y')-loadedHeight-interfaceHeight;settings.mh=settings.h&&settings.h<settings.mh?settings.h:settings.mh;}
href=settings.href;$loadingOverlay.show();$loadingGraphic.show();if(settings.inline){$('<div id="cboxInlineTemp" />').hide().insertBefore($(href)[0]).bind(cbox_load+' '+cbox_cleanup,function(){$(this).replaceWith($loaded.children());});resize($(href));}else if(settings.iframe){resize(" ");}else if(settings.html){resize(settings.html);}else if(isImage(href)){img=new Image();img.onload=function(){var percent;img.onload=null;img.id='cboxPhoto';$(img).css({margin:'auto',border:'none',display:'block',cssFloat:'left'});if(settings.scalePhotos){setResize=function(){img.height-=img.height*percent;img.width-=img.width*percent;};if(settings.mw&&img.width>settings.mw){percent=(img.width-settings.mw)/img.width;setResize();}
if(settings.mh&&img.height>settings.mh){percent=(img.height-settings.mh)/img.height;setResize();}}
if(settings.h){img.style.marginTop=Math.max(settings.h-img.height,0)/2+'px';}
resize(img);if($related.length>1){$(img).css({cursor:'pointer'}).click(cboxPublic.next);}
if(isIE){img.style.msInterpolationMode='bicubic';}};img.src=href;}else{$('<div />').appendTo($loadingBay).load(href,function(data,textStatus){if(textStatus==="success"){resize(this);}else{resize($("<p>Request unsuccessful.</p>"));}});}};cboxPublic.next=function(){if(!active){index=index<$related.length-1?index+1:0;cboxPublic.load();}};cboxPublic.prev=function(){if(!active){index=index>0?index-1:$related.length-1;cboxPublic.load();}};cboxPublic.slideshow=function(){var stop,timeOut,className='cboxSlideshow_';$slideshow.bind(cbox_closed,function(){$slideshow.unbind();clearTimeout(timeOut);$cbox.removeClass(className+"off"+" "+className+"on");});function start(){$slideshow.text(settings.slideshowStop).bind(cbox_complete,function(){timeOut=setTimeout(cboxPublic.next,settings.slideshowSpeed);}).bind(cbox_load,function(){clearTimeout(timeOut);}).one("click",function(){stop();$(this).removeClass(hover);});$cbox.removeClass(className+"off").addClass(className+"on");}
stop=function(){clearTimeout(timeOut);$slideshow.text(settings.slideshowStart).unbind(cbox_complete+' '+cbox_load).one("click",function(){start();timeOut=setTimeout(cboxPublic.next,settings.slideshowSpeed);$(this).removeClass(hover);});$cbox.removeClass(className+"on").addClass(className+"off");};if(settings.slideshow&&$related.length>1){if(settings.slideshowAuto){start();}else{stop();}}};cboxPublic.close=function(){$.event.trigger(cbox_cleanup);if(settings.onCleanup){settings.onCleanup.call(element);}
open=FALSE;$(document).unbind("keydown.cbox_close keydown.cbox_arrows");$window.unbind(cbox_resize+' resize.cboxie6 scroll.cboxie6');$overlay.css({cursor:'auto'}).fadeOut('fast');$cbox.stop(TRUE,FALSE).fadeOut('fast',function(){$('#colorbox iframe').attr('src','about:blank');$loaded.remove();$cbox.css({'opacity':1});try{bookmark.focus();}catch(er){}
$.event.trigger(cbox_closed);if(settings.onClosed){settings.onClosed.call(element);}});};cboxPublic.element=function(){return $(element);};cboxPublic.settings=defaults;$(cboxPublic.init);}(jQuery));;(function($){$.fn.achtung=function(options)
{var isMethodCall=(typeof options==='string'),args=Array.prototype.slice.call(arguments,0),name='achtung';return this.each(function(){var instance=$.data(this,name);if(isMethodCall&&options.substring(0,1)==='_'){return this;}
(!instance&&!isMethodCall&&$.data(this,name,new $.achtung(this))._init(args));(instance&&isMethodCall&&$.isFunction(instance[options])&&instance[options].apply(instance,args.slice(1)));});};$.achtung=function(element)
{var args=Array.prototype.slice.call(arguments,0),$el;if(!element||!element.nodeType){$el=$('<div />');return $el.achtung.apply($el,args);}
this.$container=$(element);};$.extend($.achtung,{version:'0.3.0',$overlay:false,defaults:{timeout:10,disableClose:false,icon:false,className:'',animateClassSwitch:false,showEffects:{'opacity':'toggle','height':'toggle'},hideEffects:{'opacity':'toggle','height':'toggle'},showEffectDuration:500,hideEffectDuration:700}});$.extend($.achtung.prototype,{$container:false,closeTimer:false,options:{},_init:function(args)
{var o,self=this;args=$.isArray(args)?args:[];args.unshift($.achtung.defaults);args.unshift({});o=this.options=$.extend.apply($,args);if(!$.achtung.$overlay){$.achtung.$overlay=$('<div id="achtung-overlay"></div>').appendTo(document.body);}
if(!o.disableClose){$('<span class="achtung-close-button ui-icon ui-icon-close" />').click(function(){self.close();}).hover(function(){$(this).addClass('achtung-close-button-hover');},function(){$(this).removeClass('achtung-close-button-hover');}).prependTo(this.$container);}
this.changeIcon(o.icon,true);if(o.message){this.$container.append($('<span class="achtung-message">'+o.message+'</span>'));}
(o.className&&this.$container.addClass(o.className));(o.css&&this.$container.css(o.css));this.$container.addClass('achtung').appendTo($.achtung.$overlay);if(o.showEffects){this.$container.animate(o.showEffects,o.showEffectDuration);}else{this.$container.show();}
if(o.timeout>0){this.timeout(o.timeout);}},timeout:function(timeout)
{var self=this;if(this.closeTimer){clearTimeout(this.closeTimer);}
this.closeTimer=setTimeout(function(){self.close();},timeout*1000);this.options.timeout=timeout;},changeClass:function(newClass)
{var self=this;if(this.options.className===newClass){return;}
this.$container.queue(function(){if(!self.options.animateClassSwitch||/webkit/.test(navigator.userAgent.toLowerCase())||!$.isFunction($.fn.switchClass)){self.$container.removeClass(self.options.className);self.$container.addClass(newClass);}else{self.$container.switchClass(self.options.className,newClass,500);}
self.options.className=newClass;self.$container.dequeue();});},changeIcon:function(newIcon,force)
{var self=this;if((force!==true||newIcon===false)&&this.options.icon===newIcon){return;}
if(force||this.options.icon===false){this.$container.prepend($('<span class="achtung-message-icon ui-icon '+newIcon+'" />'));this.options.icon=newIcon;return;}else if(newIcon===false){this.$container.find('.achtung-message-icon').remove();this.options.icon=false;return;}
this.$container.queue(function(){var $span=$('.achtung-message-icon',self.$container);if(!self.options.animateClassSwitch||/webkit/.test(navigator.userAgent.toLowerCase())||!$.isFunction($.fn.switchClass)){$span.removeClass(self.options.icon);$span.addClass(newIcon);}else{$span.switchClass(self.options.icon,newIcon,500);}
self.options.icon=newIcon;self.$container.dequeue();});},changeMessage:function(newMessage)
{this.$container.queue(function(){$('.achtung-message',$(this)).html(newMessage);$(this).dequeue();});},update:function(options)
{(options.className&&this.changeClass(options.className));(options.css&&this.$container.css(options.css));(typeof(options.icon)!=='undefined'&&this.changeIcon(options.icon));(options.message&&this.changeMessage(options.message));(options.timeout&&this.timeout(options.timeout));},close:function()
{var o=this.options,$container=this.$container;if(o.hideEffects){this.$container.animate(o.hideEffects,o.hideEffectDuration);}else{this.$container.hide();}
$container.queue(function(){$container.removeData('achtung');$container.remove();if($.achtung.$overlay&&$.achtung.$overlay.is(':empty')){$.achtung.$overlay.remove();$.achtung.$overlay=false;}
$container.dequeue();});}});})(jQuery);;(function($){$.suggestClick=function(input,options){var $input=$(input).attr("autocomplete","off");var $results=$(document.createElement("ul"));var performing=false;var timeout=false;var prevLength=0;var cache=[];var cachedb=[];$results.addClass(options.resultsClass).appendTo(options.positionIn?options.positionIn:'body');$(window).resize(resetPosition);$input.focus(function(){resetPosition();suggest();});$input.blur(function(){setTimeout(function(){$results.hide()},200);});try{if(typeof bgiframe=='function'){$results.bgiframe();}}catch(e){}
if($.browser.mozilla){$input.keypress(processKey);}else{$input.keydown(processKey);}
function resetPosition(){if($(this).attr("autocomplete")){$input=$(this).attr("autocomplete","off");}
if(!options.noPosition){if(!options.positionIn&&options.positionElement){var top=$(options.positionElement).offset().top+$(options.positionElement).outerHeight();var left=$(options.positionElement).offset().left;var width=$(options.positionElement).width();}else if(!options.positionIn){var top=$input.offset().top+input.offsetHeight;var left=$input.offset().left;var width=$input.width()+4;}
$results.css({top:top+'px',left:left+'px',width:width+'px'});}}
function processKey(e){if((/27$|38$|40$/.test(e.keyCode)&&$results.is(':visible'))||(/^13$|^9$/.test(e.keyCode)&&getCurrentResult())){if(e.preventDefault){e.preventDefault();}
if(e.stopPropagation){e.stopPropagation();}
e.cancelBubble=true;e.returnValue=false;switch(e.keyCode){case 38:prevResult();break;case 40:nextResult();break;case 9:case 13:selectCurrentResult();break;case 27:$results.hide();break;}}else{setTimeout(doSuggest,options.delay);}}
function doSuggest(){if($input.val().length!=prevLength){if(performing){setTimeout(doSuggest,options.delay);}else{if(timeout){clearTimeout(timeout);}
var q=$.trim($input.val()).toLowerCase();var delay=cache[q]==undefined?0:(options.delay*5);prevLength=$input.val().length;if(delay){timeout=setTimeout(suggest,delay);}else{suggest();}}}}
function suggest(){var q=$.trim($input.val()).toLowerCase();if(q.length>=options.minchars){cached=checkCache(q);if(cached){displayItems(cached);}else{performing=true;$.get(options.source,{q:q,l:options.limit},function(txt){$results.hide();var items=parseTxt(txt);displayItems(items);addToCache(q,items);performing=false;});}}else{$results.hide();}}
function checkCache(q){if(cache[q]==undefined&&q.length>=options.minchars){var search='';var attempted=false;for(x in q){search+=q[x];if(search.length>=options.minchars&&cachedb[search]!=undefined&&cache[search]!=undefined&&!cache[search].length){attempted=true;return[];}}
if(attempted){return[];}else{return false;}}else if(cache[q]==undefined){return false;}else{return cache[q];}}
function addToCache(q,items){if(cache[q]==undefined){cache[q]=items;cachedb[q]=true;}}
function displayItems(items){if(!items){return;}
if(!items.length){$results.hide();return;}
var html='';for(i in items){html+='<li>'+items[i]+'</li>';}
$results.html(html).show();try{if(typeof bgiframe=='function'){$results.bgiframe();}}catch(e){}
$results.children('li').mouseover(function(){$results.children('li').removeClass(options.selectClass).removeClass(options.selectClass+"next");$(this).addClass(options.selectClass).next().addClass(options.selectClass+"next");});}
function parseTxt(txt){var items=[];var tokens=txt.split(options.delimiter);for(var i=0;i<tokens.length;i++){var token=$.trim(tokens[i]);if(token){items[items.length]=token;}}
return items;}
function getCurrentResult(){if(!$results.is(':visible')){return false;}
var $currentResult=$results.children('li.'+options.selectClass);if(!$currentResult.length){$currentResult=false;}
return $currentResult;}
function selectCurrentResult(){$currentResult=getCurrentResult();if($currentResult){location.href=$currentResult.find('a').attr('href');}}
function nextResult(){$currentResult=getCurrentResult();$results.children('li').removeClass(options.selectClass).removeClass(options.selectClass+"next");if($currentResult){var applyto=$currentResult.next();}else{var applyto=$results.children('li:first-child');}
applyto.addClass(options.selectClass).next().addClass(options.selectClass+"next");}
function prevResult(){$currentResult=getCurrentResult();$results.children('li').removeClass(options.selectClass).removeClass(options.selectClass+"next");if($currentResult){var applyto=$currentResult.addClass(options.selectClass+"next").prev();}else{var applyto=$results.children('li:last-child');}
applyto.addClass(options.selectClass);}}
$.fn.suggestClick=function(source,options){if(!source){return;}
options=options||{};options.source=source;options.delay=options.delay||100;options.limit=options.limit||10;options.resultsClass=options.resultsClass||'suggest_results';options.selectClass=options.selectClass||'suggest_over';options.noPosition=options.noPosition||false;options.positionElement=options.positionElement||false;options.positionIn=options.positionIn||false;options.minchars=options.minchars||2;options.delimiter=options.delimiter||'\n';options.onSelect=options.onSelect||false;this.each(function(){new $.suggestClick(this,options);});return this;};})(jQuery);