                             GLfloat     moveSet[]   =  {0, 0, 0, 0};
                             GLfloat     wood_LIGHT_POSITION_01[]   =  {-0.168917, 4.73002, -0.115183, 1};
                             GLfloat     plant_01_Shadow_ROTATE[]   =  {5.07, 5.39, 4.84, 43.1701};
                             GLfloat     goldenSunset_LIGHT_POSITION_01[]   =  {-0.068917, 3.9, -0.715183, 1};
                             GLfloat     adjust         =   -5;
                             GLfloat     globalLinearAttenuation          =   0.09;
                             GLfloat     adjustModelShadow_02_ROTATION          =   25;
                             GLfloat     tileJump[]          =  {0, 0, 0, 1.0};
                             GLfloat     pyramidTile_counter =   -0.18;
                             GLfloat     mainBodyPosition[]  =  {0, 0, 0, 0};
                             //--------------------------------------------------------;
                             GLfloat     eyePosition[]                     =  {-0.25, -4.49996, 7.45011, 1.0};
                             GLfloat     look_LEFT_RIGHT                   = 0.8;
                             GLfloat     look_UP_DOWN                      = 8.6;
